/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 90
#define ALIAS_COUNT 0
#define TOKEN_COUNT 56
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_model = 2,
  anon_sym_module = 3,
  anon_sym_schema = 4,
  anon_sym_COLON = 5,
  sym_version = 6,
  anon_sym_DQUOTE = 7,
  anon_sym_SQUOTE = 8,
  anon_sym_contents = 9,
  anon_sym_DASH = 10,
  sym_file = 11,
  anon_sym_extend = 12,
  anon_sym_type = 13,
  anon_sym_relations = 14,
  anon_sym_define = 15,
  anon_sym_or = 16,
  anon_sym_and = 17,
  anon_sym_butnot = 18,
  anon_sym_LPAREN = 19,
  anon_sym_RPAREN = 20,
  anon_sym_LBRACK = 21,
  anon_sym_COMMA = 22,
  anon_sym_RBRACK = 23,
  sym_relation_ref = 24,
  sym_all = 25,
  anon_sym_with = 26,
  anon_sym_from = 27,
  anon_sym_condition = 28,
  anon_sym_bool = 29,
  anon_sym_string = 30,
  anon_sym_int = 31,
  anon_sym_uint = 32,
  anon_sym_double = 33,
  anon_sym_duration = 34,
  anon_sym_timestamp = 35,
  anon_sym_ipaddress = 36,
  anon_sym_map = 37,
  anon_sym_list = 38,
  anon_sym_LT = 39,
  anon_sym_GT = 40,
  anon_sym_LBRACE = 41,
  anon_sym_RBRACE = 42,
  anon_sym_DOT = 43,
  anon_sym_QMARK = 44,
  sym_condition_operator = 45,
  anon_sym_true = 46,
  anon_sym_false = 47,
  sym_null = 48,
  sym_float = 49,
  sym_int = 50,
  sym_uint = 51,
  sym_bytes = 52,
  sym_string = 53,
  sym_extended_identifier = 54,
  sym_comment = 55,
  sym_source_file = 56,
  sym_module = 57,
  sym_schema = 58,
  sym_quoted_schema = 59,
  sym_quoted_version = 60,
  sym_contents = 61,
  sym_type_declaration = 62,
  sym_relations = 63,
  sym_definition = 64,
  sym_relation_def = 65,
  sym_relation_term = 66,
  sym_binary_relation = 67,
  sym_parenthesized_relation = 68,
  sym_direct_relationship = 69,
  sym_direct_relationship_item = 70,
  sym_conditional = 71,
  sym_indirect_relation = 72,
  sym_condition_declaration = 73,
  sym_param = 74,
  sym_type_identifier = 75,
  sym_simple_type_identifier = 76,
  sym_container_type_identifier = 77,
  sym_condition_body = 78,
  sym__condition_item = 79,
  sym_parenthesized_condition = 80,
  sym_bracket_condition = 81,
  sym_braced_condition = 82,
  sym_boolean = 83,
  aux_sym_source_file_repeat1 = 84,
  aux_sym_contents_repeat1 = 85,
  aux_sym_relations_repeat1 = 86,
  aux_sym_direct_relationship_repeat1 = 87,
  aux_sym_condition_declaration_repeat1 = 88,
  aux_sym_condition_body_repeat1 = 89,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_model] = "model",
  [anon_sym_module] = "module",
  [anon_sym_schema] = "schema",
  [anon_sym_COLON] = ":",
  [sym_version] = "version",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_contents] = "contents",
  [anon_sym_DASH] = "-",
  [sym_file] = "file",
  [anon_sym_extend] = "extend",
  [anon_sym_type] = "type",
  [anon_sym_relations] = "relations",
  [anon_sym_define] = "define",
  [anon_sym_or] = "operator",
  [anon_sym_and] = "operator",
  [anon_sym_butnot] = "operator",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_relation_ref] = "relation_ref",
  [sym_all] = "all",
  [anon_sym_with] = "with",
  [anon_sym_from] = "from",
  [anon_sym_condition] = "condition",
  [anon_sym_bool] = "bool",
  [anon_sym_string] = "string",
  [anon_sym_int] = "int",
  [anon_sym_uint] = "uint",
  [anon_sym_double] = "double",
  [anon_sym_duration] = "duration",
  [anon_sym_timestamp] = "timestamp",
  [anon_sym_ipaddress] = "ipaddress",
  [anon_sym_map] = "map",
  [anon_sym_list] = "list",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT] = ".",
  [anon_sym_QMARK] = "\?",
  [sym_condition_operator] = "condition_operator",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_float] = "float",
  [sym_int] = "int",
  [sym_uint] = "uint",
  [sym_bytes] = "bytes",
  [sym_string] = "string",
  [sym_extended_identifier] = "extended_identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_module] = "module",
  [sym_schema] = "schema",
  [sym_quoted_schema] = "schema",
  [sym_quoted_version] = "quoted_version",
  [sym_contents] = "contents",
  [sym_type_declaration] = "type_declaration",
  [sym_relations] = "relations",
  [sym_definition] = "definition",
  [sym_relation_def] = "relation_def",
  [sym_relation_term] = "relation_term",
  [sym_binary_relation] = "binary_relation",
  [sym_parenthesized_relation] = "parenthesized_relation",
  [sym_direct_relationship] = "direct_relationship",
  [sym_direct_relationship_item] = "direct_relationship_item",
  [sym_conditional] = "conditional",
  [sym_indirect_relation] = "indirect_relation",
  [sym_condition_declaration] = "condition_declaration",
  [sym_param] = "param",
  [sym_type_identifier] = "type_identifier",
  [sym_simple_type_identifier] = "simple_type_identifier",
  [sym_container_type_identifier] = "container_type_identifier",
  [sym_condition_body] = "condition_body",
  [sym__condition_item] = "_condition_item",
  [sym_parenthesized_condition] = "parenthesized_condition",
  [sym_bracket_condition] = "bracket_condition",
  [sym_braced_condition] = "braced_condition",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_contents_repeat1] = "contents_repeat1",
  [aux_sym_relations_repeat1] = "relations_repeat1",
  [aux_sym_direct_relationship_repeat1] = "direct_relationship_repeat1",
  [aux_sym_condition_declaration_repeat1] = "condition_declaration_repeat1",
  [aux_sym_condition_body_repeat1] = "condition_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_model] = sym_model,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_schema] = anon_sym_schema,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_version] = sym_version,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_contents] = anon_sym_contents,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_file] = sym_file,
  [anon_sym_extend] = anon_sym_extend,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_relations] = anon_sym_relations,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_or,
  [anon_sym_butnot] = anon_sym_or,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_relation_ref] = sym_relation_ref,
  [sym_all] = sym_all,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_condition] = anon_sym_condition,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_double] = anon_sym_double,
  [anon_sym_duration] = anon_sym_duration,
  [anon_sym_timestamp] = anon_sym_timestamp,
  [anon_sym_ipaddress] = anon_sym_ipaddress,
  [anon_sym_map] = anon_sym_map,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [sym_condition_operator] = sym_condition_operator,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_float] = sym_float,
  [sym_int] = sym_int,
  [sym_uint] = sym_uint,
  [sym_bytes] = sym_bytes,
  [sym_string] = sym_string,
  [sym_extended_identifier] = sym_extended_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_module] = sym_module,
  [sym_schema] = sym_schema,
  [sym_quoted_schema] = sym_schema,
  [sym_quoted_version] = sym_quoted_version,
  [sym_contents] = sym_contents,
  [sym_type_declaration] = sym_type_declaration,
  [sym_relations] = sym_relations,
  [sym_definition] = sym_definition,
  [sym_relation_def] = sym_relation_def,
  [sym_relation_term] = sym_relation_term,
  [sym_binary_relation] = sym_binary_relation,
  [sym_parenthesized_relation] = sym_parenthesized_relation,
  [sym_direct_relationship] = sym_direct_relationship,
  [sym_direct_relationship_item] = sym_direct_relationship_item,
  [sym_conditional] = sym_conditional,
  [sym_indirect_relation] = sym_indirect_relation,
  [sym_condition_declaration] = sym_condition_declaration,
  [sym_param] = sym_param,
  [sym_type_identifier] = sym_type_identifier,
  [sym_simple_type_identifier] = sym_simple_type_identifier,
  [sym_container_type_identifier] = sym_container_type_identifier,
  [sym_condition_body] = sym_condition_body,
  [sym__condition_item] = sym__condition_item,
  [sym_parenthesized_condition] = sym_parenthesized_condition,
  [sym_bracket_condition] = sym_bracket_condition,
  [sym_braced_condition] = sym_braced_condition,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_contents_repeat1] = aux_sym_contents_repeat1,
  [aux_sym_relations_repeat1] = aux_sym_relations_repeat1,
  [aux_sym_direct_relationship_repeat1] = aux_sym_direct_relationship_repeat1,
  [aux_sym_condition_declaration_repeat1] = aux_sym_condition_declaration_repeat1,
  [aux_sym_condition_body_repeat1] = aux_sym_condition_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_model] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_schema] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contents] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_extend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_relations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_butnot] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_relation_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_all] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_condition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_double] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_duration] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_timestamp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ipaddress] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [sym_condition_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_uint] = {
    .visible = true,
    .named = true,
  },
  [sym_bytes] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_extended_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_version] = {
    .visible = true,
    .named = true,
  },
  [sym_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_relations] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_relation_def] = {
    .visible = true,
    .named = true,
  },
  [sym_relation_term] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_binary_relation] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_relation] = {
    .visible = true,
    .named = true,
  },
  [sym_direct_relationship] = {
    .visible = true,
    .named = true,
  },
  [sym_direct_relationship_item] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_indirect_relation] = {
    .visible = true,
    .named = true,
  },
  [sym_condition_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_container_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_condition_body] = {
    .visible = true,
    .named = true,
  },
  [sym__condition_item] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_contents_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_relations_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_direct_relationship_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_condition_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_condition_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_condition = 2,
  field_left = 3,
  field_name = 4,
  field_operator = 5,
  field_relation = 6,
  field_right = 7,
  field_tupleset = 8,
  field_type = 9,
  field_value = 10,
  field_version = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_condition] = "condition",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_relation] = "relation",
  [field_right] = "right",
  [field_tupleset] = "tupleset",
  [field_type] = "type",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 3},
  [11] = {.index = 18, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_version, 1},
  [2] =
    {field_name, 2},
  [3] =
    {field_body, 4},
    {field_name, 1},
  [5] =
    {field_name, 0},
    {field_type, 2},
  [7] =
    {field_body, 5},
    {field_name, 1},
  [9] =
    {field_relation, 1},
    {field_value, 3},
  [11] =
    {field_body, 6},
    {field_name, 1},
  [13] =
    {field_relation, 0},
    {field_tupleset, 2},
  [15] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [18] =
    {field_condition, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_relation_term,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_relation_term] = {.index = 0, .length = 4},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_direct_relationship,
    sym_extended_identifier,
    sym_indirect_relation,
    sym_parenthesized_relation,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '!', 53,
        '"', 32,
        '#', 75,
        '&', 7,
        '\'', 33,
        '(', 37,
        ')', 38,
        ',', 40,
        '-', 34,
        '.', 50,
        '0', 57,
        ':', 30,
        '<', 45,
        '=', 12,
        '>', 47,
        '?', 51,
        'B', 73,
        '[', 39,
        ']', 41,
        'b', 72,
        'i', 70,
        '{', 48,
        '|', 16,
        '}', 49,
        '%', 52,
        '*', 52,
        '+', 52,
        '/', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 53,
        '"', 2,
        '#', 75,
        '&', 7,
        '\'', 8,
        '(', 37,
        ')', 38,
        ',', 40,
        '.', 50,
        '0', 57,
        ':', 30,
        '<', 53,
        '=', 12,
        '>', 53,
        '?', 51,
        '[', 39,
        ']', 41,
        'i', 65,
        '{', 48,
        '|', 16,
        '}', 49,
        'B', 64,
        'b', 64,
        '%', 52,
        '*', 52,
        '+', 52,
        '-', 52,
        '/', 52,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(75);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == '[') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(75);
      if (lookahead == ']') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == '&') ADVANCE(52);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(62);
      if (lookahead == '\\') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(43);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == '|') ADVANCE(52);
      END_STATE();
    case 17:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 22:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 24:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 26:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 27:
      if (eof) ADVANCE(29);
      if (lookahead == '#') ADVANCE(75);
      if (lookahead == ')') ADVANCE(38);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '<') ADVANCE(44);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == ']') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '#') ADVANCE(75);
      if (lookahead == ')') ADVANCE(38);
      if (lookahead == 'b') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_version);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_file);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_butnot);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_relation_ref);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_all);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_condition_operator);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_condition_operator);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_condition_operator);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == 'x') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_uint);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_bytes);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_extended_identifier);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == ':') ADVANCE(10);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_extended_identifier);
      if (lookahead == 'n') ADVANCE(73);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(74);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_extended_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(74);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_extended_identifier);
      if (lookahead == 'u') ADVANCE(71);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(74);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_extended_identifier);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(74);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_extended_identifier);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(75);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'i', 7,
        'l', 8,
        'm', 9,
        'n', 10,
        'o', 11,
        'r', 12,
        's', 13,
        't', 14,
        'u', 15,
        'w', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(21);
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == 'x') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(34);
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == 'r') ADVANCE(37);
      if (lookahead == 'y') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(41);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(57);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 36:
      if (lookahead == 'm') ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 38:
      if (lookahead == 'p') ADVANCE(61);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 42:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(65);
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 45:
      if (lookahead == 'b') ADVANCE(68);
      END_STATE();
    case 46:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 48:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 51:
      if (lookahead == 'd') ADVANCE(73);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(75);
      if (lookahead == 'u') ADVANCE(76);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(78);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(80);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(84);
      END_STATE();
    case 63:
      if (lookahead == 'h') ADVANCE(85);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 65:
      if (lookahead == 'i') ADVANCE(86);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 67:
      if (lookahead == 'n') ADVANCE(88);
      END_STATE();
    case 68:
      if (lookahead == 'l') ADVANCE(89);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 70:
      if (lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 71:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 73:
      if (lookahead == 'd') ADVANCE(93);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 75:
      if (lookahead == 'l') ADVANCE(94);
      END_STATE();
    case 76:
      if (lookahead == 'l') ADVANCE(95);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 79:
      if (lookahead == 'm') ADVANCE(97);
      END_STATE();
    case 80:
      if (lookahead == 'n') ADVANCE(98);
      END_STATE();
    case 81:
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_uint);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 86:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 87:
      if (lookahead == 'n') ADVANCE(101);
      END_STATE();
    case 88:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 89:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 90:
      if (lookahead == 'i') ADVANCE(104);
      END_STATE();
    case 91:
      if (lookahead == 'd') ADVANCE(105);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 93:
      if (lookahead == 'r') ADVANCE(106);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_model);
      END_STATE();
    case 95:
      if (lookahead == 'e') ADVANCE(107);
      END_STATE();
    case 96:
      if (lookahead == 'i') ADVANCE(108);
      END_STATE();
    case 97:
      if (lookahead == 'a') ADVANCE(109);
      END_STATE();
    case 98:
      if (lookahead == 'g') ADVANCE(110);
      END_STATE();
    case 99:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 100:
      if (lookahead == 'i') ADVANCE(112);
      END_STATE();
    case 101:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_double);
      END_STATE();
    case 104:
      if (lookahead == 'o') ADVANCE(114);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_extend);
      END_STATE();
    case 106:
      if (lookahead == 'e') ADVANCE(115);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 108:
      if (lookahead == 'o') ADVANCE(116);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_schema);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 111:
      if (lookahead == 'a') ADVANCE(117);
      END_STATE();
    case 112:
      if (lookahead == 'o') ADVANCE(118);
      END_STATE();
    case 113:
      if (lookahead == 's') ADVANCE(119);
      END_STATE();
    case 114:
      if (lookahead == 'n') ADVANCE(120);
      END_STATE();
    case 115:
      if (lookahead == 's') ADVANCE(121);
      END_STATE();
    case 116:
      if (lookahead == 'n') ADVANCE(122);
      END_STATE();
    case 117:
      if (lookahead == 'm') ADVANCE(123);
      END_STATE();
    case 118:
      if (lookahead == 'n') ADVANCE(124);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_contents);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_duration);
      END_STATE();
    case 121:
      if (lookahead == 's') ADVANCE(125);
      END_STATE();
    case 122:
      if (lookahead == 's') ADVANCE(126);
      END_STATE();
    case 123:
      if (lookahead == 'p') ADVANCE(127);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_condition);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_ipaddress);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_relations);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_timestamp);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 27},
  [19] = {.lex_state = 28},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 28},
  [24] = {.lex_state = 28},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 27},
  [27] = {.lex_state = 28},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 28},
  [31] = {.lex_state = 28},
  [32] = {.lex_state = 28},
  [33] = {.lex_state = 28},
  [34] = {.lex_state = 28},
  [35] = {.lex_state = 28},
  [36] = {.lex_state = 28},
  [37] = {.lex_state = 27},
  [38] = {.lex_state = 27},
  [39] = {.lex_state = 27},
  [40] = {.lex_state = 27},
  [41] = {.lex_state = 27},
  [42] = {.lex_state = 27},
  [43] = {.lex_state = 27},
  [44] = {.lex_state = 27},
  [45] = {.lex_state = 27},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 27},
  [48] = {.lex_state = 27},
  [49] = {.lex_state = 27},
  [50] = {.lex_state = 27},
  [51] = {.lex_state = 27},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 27},
  [54] = {.lex_state = 27},
  [55] = {.lex_state = 28},
  [56] = {.lex_state = 27},
  [57] = {.lex_state = 27},
  [58] = {.lex_state = 27},
  [59] = {.lex_state = 27},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 27},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 27},
  [65] = {.lex_state = 27},
  [66] = {.lex_state = 27},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 27},
  [69] = {.lex_state = 27},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 27},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 27},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 27},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 27},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 27},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 27},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 27},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 27},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 27},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 27},
  [100] = {.lex_state = 27},
  [101] = {.lex_state = 27},
  [102] = {.lex_state = 27},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 4},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 27},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_model] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_schema] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_contents] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_extend] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_relations] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_butnot] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_condition] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_double] = ACTIONS(1),
    [anon_sym_duration] = ACTIONS(1),
    [anon_sym_timestamp] = ACTIONS(1),
    [anon_sym_ipaddress] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [sym_condition_operator] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_uint] = ACTIONS(1),
    [sym_bytes] = ACTIONS(1),
    [sym_extended_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(107),
    [sym_module] = STATE(43),
    [sym_quoted_schema] = STATE(59),
    [sym_model] = ACTIONS(5),
    [anon_sym_module] = ACTIONS(7),
    [anon_sym_schema] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(22), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(28), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(20), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
    ACTIONS(11), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(2), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(14), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [46] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(31), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(7), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(33), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [90] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(8), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(47), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [134] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(55), 1,
      anon_sym_RBRACK,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(51), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(9), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(53), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [178] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(57), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(10), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(59), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [222] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(63), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(2), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(65), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [266] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(63), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(2), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(65), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [310] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(63), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(2), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(65), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [354] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(63), 5,
      anon_sym_DOT,
      sym_condition_operator,
      sym_null,
      sym_int,
      sym_identifier,
    STATE(2), 6,
      sym__condition_item,
      sym_parenthesized_condition,
      sym_bracket_condition,
      sym_braced_condition,
      sym_boolean,
      aux_sym_condition_body_repeat1,
    ACTIONS(65), 7,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [398] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 7,
      anon_sym_DOT,
      sym_condition_operator,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_int,
      sym_identifier,
    ACTIONS(77), 13,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 7,
      anon_sym_DOT,
      sym_condition_operator,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_int,
      sym_identifier,
    ACTIONS(81), 13,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [454] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 7,
      anon_sym_DOT,
      sym_condition_operator,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_int,
      sym_identifier,
    ACTIONS(85), 13,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [482] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 7,
      anon_sym_DOT,
      sym_condition_operator,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_int,
      sym_identifier,
    ACTIONS(89), 13,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [510] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 7,
      anon_sym_DOT,
      sym_condition_operator,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_int,
      sym_identifier,
    ACTIONS(93), 13,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [538] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 7,
      anon_sym_DOT,
      sym_condition_operator,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_int,
      sym_identifier,
    ACTIONS(97), 13,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [566] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 7,
      anon_sym_DOT,
      sym_condition_operator,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_int,
      sym_identifier,
    ACTIONS(101), 13,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_QMARK,
      sym_float,
      sym_uint,
      sym_bytes,
      sym_string,
  [594] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(75), 1,
      sym_type_identifier,
    ACTIONS(105), 2,
      anon_sym_map,
      anon_sym_list,
    STATE(78), 2,
      sym_simple_type_identifier,
      sym_container_type_identifier,
    ACTIONS(103), 8,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_int,
      anon_sym_uint,
      anon_sym_double,
      anon_sym_duration,
      anon_sym_timestamp,
      anon_sym_ipaddress,
  [619] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_from,
    ACTIONS(107), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [637] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      sym_extended_identifier,
    STATE(35), 1,
      sym_relation_def,
    STATE(23), 2,
      sym_relation_term,
      sym_binary_relation,
    STATE(24), 3,
      sym_parenthesized_relation,
      sym_direct_relationship,
      sym_indirect_relation,
  [662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [677] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      sym_extended_identifier,
    STATE(55), 1,
      sym_relation_def,
    STATE(23), 2,
      sym_relation_term,
      sym_binary_relation,
    STATE(24), 3,
      sym_parenthesized_relation,
      sym_direct_relationship,
      sym_indirect_relation,
  [702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [732] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      sym_extended_identifier,
    STATE(36), 1,
      sym_relation_def,
    STATE(23), 2,
      sym_relation_term,
      sym_binary_relation,
    STATE(24), 3,
      sym_parenthesized_relation,
      sym_direct_relationship,
      sym_indirect_relation,
  [757] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(95), 1,
      sym_simple_type_identifier,
    ACTIONS(103), 8,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_int,
      anon_sym_uint,
      anon_sym_double,
      anon_sym_duration,
      anon_sym_timestamp,
      anon_sym_ipaddress,
  [774] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [789] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      sym_extended_identifier,
    STATE(33), 1,
      sym_relation_def,
    STATE(23), 2,
      sym_relation_term,
      sym_binary_relation,
    STATE(24), 3,
      sym_parenthesized_relation,
      sym_direct_relationship,
      sym_indirect_relation,
  [814] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      anon_sym_LBRACK,
    ACTIONS(115), 1,
      sym_extended_identifier,
    STATE(34), 1,
      sym_relation_def,
    STATE(23), 2,
      sym_relation_term,
      sym_binary_relation,
    STATE(24), 3,
      sym_parenthesized_relation,
      sym_direct_relationship,
      sym_indirect_relation,
  [839] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [854] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [869] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [884] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_and,
    ACTIONS(133), 1,
      anon_sym_butnot,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_RPAREN,
      anon_sym_condition,
  [903] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_butnot,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_RPAREN,
      anon_sym_condition,
  [920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 9,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_or,
      anon_sym_and,
      anon_sym_butnot,
      anon_sym_RPAREN,
      anon_sym_condition,
  [935] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_and,
    ACTIONS(133), 1,
      anon_sym_butnot,
    ACTIONS(137), 1,
      anon_sym_or,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_define,
      anon_sym_condition,
  [955] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      anon_sym_extend,
    ACTIONS(143), 1,
      anon_sym_type,
    ACTIONS(145), 1,
      anon_sym_condition,
    STATE(38), 3,
      sym_type_declaration,
      sym_condition_declaration,
      aux_sym_source_file_repeat1,
  [976] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_extend,
    ACTIONS(143), 1,
      anon_sym_type,
    ACTIONS(145), 1,
      anon_sym_condition,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    STATE(40), 3,
      sym_type_declaration,
      sym_condition_declaration,
      aux_sym_source_file_repeat1,
  [997] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_define,
    STATE(39), 2,
      sym_definition,
      aux_sym_relations_repeat1,
    ACTIONS(149), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1014] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      anon_sym_extend,
    ACTIONS(159), 1,
      anon_sym_type,
    ACTIONS(162), 1,
      anon_sym_condition,
    STATE(40), 3,
      sym_type_declaration,
      sym_condition_declaration,
      aux_sym_source_file_repeat1,
  [1035] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_define,
    STATE(39), 2,
      sym_definition,
      aux_sym_relations_repeat1,
    ACTIONS(165), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1052] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      anon_sym_extend,
    ACTIONS(143), 1,
      anon_sym_type,
    ACTIONS(145), 1,
      anon_sym_condition,
    STATE(40), 3,
      sym_type_declaration,
      sym_condition_declaration,
      aux_sym_source_file_repeat1,
  [1073] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_extend,
    ACTIONS(143), 1,
      anon_sym_type,
    ACTIONS(145), 1,
      anon_sym_condition,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    STATE(42), 3,
      sym_type_declaration,
      sym_condition_declaration,
      aux_sym_source_file_repeat1,
  [1094] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_relations,
    STATE(49), 1,
      sym_relations,
    ACTIONS(171), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1110] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_relations,
    STATE(53), 1,
      sym_relations,
    ACTIONS(175), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1126] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    ACTIONS(181), 1,
      sym_extended_identifier,
    STATE(70), 1,
      sym_direct_relationship_item,
    ACTIONS(179), 2,
      sym_relation_ref,
      sym_all,
  [1143] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1163] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1193] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_extended_identifier,
    STATE(87), 1,
      sym_direct_relationship_item,
    ACTIONS(179), 2,
      sym_relation_ref,
      sym_all,
  [1207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1217] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1227] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_and,
    ACTIONS(133), 1,
      anon_sym_butnot,
    ACTIONS(137), 1,
      anon_sym_or,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
  [1243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1253] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_with,
    STATE(83), 1,
      sym_conditional,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1267] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 4,
      ts_builtin_sym_end,
      anon_sym_extend,
      anon_sym_type,
      anon_sym_condition,
  [1277] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 1,
      anon_sym_contents,
    STATE(91), 1,
      sym_contents,
  [1290] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      aux_sym_direct_relationship_repeat1,
  [1303] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_condition_declaration_repeat1,
  [1316] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    ACTIONS(221), 1,
      anon_sym_DASH,
    STATE(66), 1,
      aux_sym_contents_repeat1,
  [1329] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_DQUOTE,
    ACTIONS(225), 1,
      anon_sym_SQUOTE,
    STATE(84), 1,
      sym_quoted_version,
  [1342] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_define,
    STATE(41), 2,
      sym_definition,
      aux_sym_relations_repeat1,
  [1353] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_param,
  [1366] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_DASH,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    STATE(69), 1,
      aux_sym_contents_repeat1,
  [1379] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_condition_declaration_repeat1,
  [1392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_GT,
  [1401] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
    ACTIONS(241), 1,
      anon_sym_DASH,
    STATE(69), 1,
      aux_sym_contents_repeat1,
  [1414] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    STATE(72), 1,
      aux_sym_direct_relationship_repeat1,
  [1427] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_condition_declaration_repeat1,
  [1440] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
    STATE(60), 1,
      aux_sym_direct_relationship_repeat1,
  [1453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      ts_builtin_sym_end,
      anon_sym_DASH,
  [1461] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_condition_body,
  [1471] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 2,
      ts_builtin_sym_end,
      anon_sym_contents,
  [1487] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_condition_body,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1505] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_schema,
    STATE(37), 1,
      sym_schema,
  [1515] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_condition_body,
  [1525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_identifier,
    STATE(82), 1,
      sym_param,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      ts_builtin_sym_end,
      anon_sym_contents,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1567] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1575] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_COLON,
  [1590] = 2,
    ACTIONS(272), 1,
      sym_file,
    ACTIONS(274), 1,
      sym_comment,
  [1597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LT,
  [1604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_identifier,
  [1618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_extended_identifier,
  [1625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_COLON,
  [1632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_GT,
  [1639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_extended_identifier,
  [1646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      sym_identifier,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_DQUOTE,
  [1660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      sym_version,
  [1667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      sym_version,
  [1674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_type,
  [1681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_version,
  [1688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_SQUOTE,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      sym_extended_identifier,
  [1702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_COLON,
  [1709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_COLON,
  [1716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      ts_builtin_sym_end,
  [1723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      sym_extended_identifier,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_LPAREN,
  [1737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 134,
  [SMALL_STATE(6)] = 178,
  [SMALL_STATE(7)] = 222,
  [SMALL_STATE(8)] = 266,
  [SMALL_STATE(9)] = 310,
  [SMALL_STATE(10)] = 354,
  [SMALL_STATE(11)] = 398,
  [SMALL_STATE(12)] = 426,
  [SMALL_STATE(13)] = 454,
  [SMALL_STATE(14)] = 482,
  [SMALL_STATE(15)] = 510,
  [SMALL_STATE(16)] = 538,
  [SMALL_STATE(17)] = 566,
  [SMALL_STATE(18)] = 594,
  [SMALL_STATE(19)] = 619,
  [SMALL_STATE(20)] = 637,
  [SMALL_STATE(21)] = 662,
  [SMALL_STATE(22)] = 677,
  [SMALL_STATE(23)] = 702,
  [SMALL_STATE(24)] = 717,
  [SMALL_STATE(25)] = 732,
  [SMALL_STATE(26)] = 757,
  [SMALL_STATE(27)] = 774,
  [SMALL_STATE(28)] = 789,
  [SMALL_STATE(29)] = 814,
  [SMALL_STATE(30)] = 839,
  [SMALL_STATE(31)] = 854,
  [SMALL_STATE(32)] = 869,
  [SMALL_STATE(33)] = 884,
  [SMALL_STATE(34)] = 903,
  [SMALL_STATE(35)] = 920,
  [SMALL_STATE(36)] = 935,
  [SMALL_STATE(37)] = 955,
  [SMALL_STATE(38)] = 976,
  [SMALL_STATE(39)] = 997,
  [SMALL_STATE(40)] = 1014,
  [SMALL_STATE(41)] = 1035,
  [SMALL_STATE(42)] = 1052,
  [SMALL_STATE(43)] = 1073,
  [SMALL_STATE(44)] = 1094,
  [SMALL_STATE(45)] = 1110,
  [SMALL_STATE(46)] = 1126,
  [SMALL_STATE(47)] = 1143,
  [SMALL_STATE(48)] = 1153,
  [SMALL_STATE(49)] = 1163,
  [SMALL_STATE(50)] = 1173,
  [SMALL_STATE(51)] = 1183,
  [SMALL_STATE(52)] = 1193,
  [SMALL_STATE(53)] = 1207,
  [SMALL_STATE(54)] = 1217,
  [SMALL_STATE(55)] = 1227,
  [SMALL_STATE(56)] = 1243,
  [SMALL_STATE(57)] = 1253,
  [SMALL_STATE(58)] = 1267,
  [SMALL_STATE(59)] = 1277,
  [SMALL_STATE(60)] = 1290,
  [SMALL_STATE(61)] = 1303,
  [SMALL_STATE(62)] = 1316,
  [SMALL_STATE(63)] = 1329,
  [SMALL_STATE(64)] = 1342,
  [SMALL_STATE(65)] = 1353,
  [SMALL_STATE(66)] = 1366,
  [SMALL_STATE(67)] = 1379,
  [SMALL_STATE(68)] = 1392,
  [SMALL_STATE(69)] = 1401,
  [SMALL_STATE(70)] = 1414,
  [SMALL_STATE(71)] = 1427,
  [SMALL_STATE(72)] = 1440,
  [SMALL_STATE(73)] = 1453,
  [SMALL_STATE(74)] = 1461,
  [SMALL_STATE(75)] = 1471,
  [SMALL_STATE(76)] = 1479,
  [SMALL_STATE(77)] = 1487,
  [SMALL_STATE(78)] = 1497,
  [SMALL_STATE(79)] = 1505,
  [SMALL_STATE(80)] = 1515,
  [SMALL_STATE(81)] = 1525,
  [SMALL_STATE(82)] = 1535,
  [SMALL_STATE(83)] = 1543,
  [SMALL_STATE(84)] = 1551,
  [SMALL_STATE(85)] = 1559,
  [SMALL_STATE(86)] = 1567,
  [SMALL_STATE(87)] = 1575,
  [SMALL_STATE(88)] = 1583,
  [SMALL_STATE(89)] = 1590,
  [SMALL_STATE(90)] = 1597,
  [SMALL_STATE(91)] = 1604,
  [SMALL_STATE(92)] = 1611,
  [SMALL_STATE(93)] = 1618,
  [SMALL_STATE(94)] = 1625,
  [SMALL_STATE(95)] = 1632,
  [SMALL_STATE(96)] = 1639,
  [SMALL_STATE(97)] = 1646,
  [SMALL_STATE(98)] = 1653,
  [SMALL_STATE(99)] = 1660,
  [SMALL_STATE(100)] = 1667,
  [SMALL_STATE(101)] = 1674,
  [SMALL_STATE(102)] = 1681,
  [SMALL_STATE(103)] = 1688,
  [SMALL_STATE(104)] = 1695,
  [SMALL_STATE(105)] = 1702,
  [SMALL_STATE(106)] = 1709,
  [SMALL_STATE(107)] = 1716,
  [SMALL_STATE(108)] = 1723,
  [SMALL_STATE(109)] = 1730,
  [SMALL_STATE(110)] = 1737,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [11] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_condition_body_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [14] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_condition_body_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_condition_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_condition_body_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_condition_body_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_condition_body_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_condition_body_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_condition, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_condition, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_condition, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_condition, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_condition, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_condition, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_condition, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_condition, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_condition, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_condition, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_condition, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_condition, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation_term, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct_relationship, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation_def, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct_relationship, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indirect_relation, 3, 0, 9),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_relation, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct_relationship, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_relation, 3, 0, 10),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4, 0, 7),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_relations_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_relations_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relations, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 3, 0, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 2, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_declaration, 6, 0, 6),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_body, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 4, 0, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_body, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 2, 0, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 3, 0, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_declaration, 7, 0, 8),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 2, 0, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct_relationship_item, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition_declaration, 5, 0, 4),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_direct_relationship_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_direct_relationship_repeat1, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_condition_declaration_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_condition_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contents, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contents, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_type_identifier, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_contents_repeat1, 2, 0, 0),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 5),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_version, 3, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct_relationship_item, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_schema, 3, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container_type_identifier, 4, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 2, 0, 11),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [306] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fga(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fga",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
