name: Fuzz Parser

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/fuzz.yaml
      - grammar.js
      - src/**
  pull_request:
    paths:
      - .github/workflows/fuzz.yaml
      - grammar.js
      - src/**

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run fuzzer
        uses: tree-sitter/fuzz-action@6a1dcff00aefd038ba418bd63732a9add4901266 # v4
