name: Fuzz Parser

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/fuzz.yaml
      - grammar.js
      - src/**
  pull_request:
    paths:
      - .github/workflows/fuzz.yaml
      - grammar.js
      - src/**

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run fuzzer
        uses: tree-sitter/fuzz-action@6a1dcff00aefd038ba418bd63732a9add4901266 # v4
